### ISSUE TITLE
installed on my system, no change in action

### ISSUE THREAD

**Issue by slvrscoobie** [badsgahhl/pihole-chrome-extension#1]
had this issue with the previous 'version' as well. my pihole is on my LAN, so I have http://192.168.1.2 for the address. Copied the API code generated, saved both. Click disable and nothing happens (click through links still blocked).

**Comment by badsgahhl** [comment]
Hello thank your for reaching out.

I need some more information for further help.

- Which PiHole Version are u using? You can find it at the bottom of your dashboard page.
- I consider if you go to http://192.168.1.2/ there is your dashboard, right? Please then go to http://192.168.1.2/api.php . Please check if this site works.
- Last open click on the extension icon. The popup should open, rightclick into the popup and click in the menu "Inspect". In the new windows click at the top "console". Please provide all the information and errors the console gives to you.

**Comment by slvrscoobie** [comment]
![Screen Shot 2020-05-01 at 12 57 11 PM](https://user-images.githubusercontent.com/13274298/80823853-55994d00-8bab-11ea-95ed-be71260ebcae.png)
Here is screen shot of the options page. 
Pi-hole Version v4.4 Web Interface Version v4.3.3 FTL Version v4.3.1
If I go to that address i get the Pi Logo with the "Pi-hole: Your black hole for Internet advertisements
Did you mean to go to the admin panel?"
Inside Console, i get a blank page.

**Comment by badsgahhl** [comment]
Hey,

does the extension show that your pihole is active?

Please go at the following url and provide a screenshot of the page. Replace <key> with your API key. The link should disable your pihole for 10 seconds.

http://192.168.1.2/api.php?auth=<key>&disable=10

**Comment by slvrscoobie** [comment]
When i click on the icon - it shows a grey box, i can turn it green but if i select say 30 seconds, then go to the dashboard, the dashboard doesnt show its disabled. and vice versa, if i disable on dashboard, the 'switch' on the extention doesnt change. 
If i go to that page, it does not load the dashboard, it asks if i want to go To the dashboard: 
![Screen Shot 2020-05-01 at 1 41 44 PM](https://user-images.githubusercontent.com/13274298/80827198-87adad80-8bb1-11ea-92bf-c117c3b946cc.png)
http://192.168.1.2/admin
entering the above doesnt disable the pihole in the admin panel

**Comment by badsgahhl** [comment]
Could you maybe send a screen of the admin panel? I never saw this kind of page at a pihole.

**Comment by slvrscoobie** [comment]
![Screen Shot 2020-05-01 at 1 49 58 PM](https://user-images.githubusercontent.com/13274298/80828076-b4ae9000-8bb2-11ea-8ce0-f569b1aa3469.png)
sure

**Comment by badsgahhl** [comment]
Perfect. Please try using http://192.168.1.2/admin in the extension settings. It should work then.

**Comment by slvrscoobie** [comment]
Bingo! now its green!

**Comment by badsgahhl** [comment]
Wonderful! I will close the issue here and add more information to the extension documentation. 

If there are any other issues or feature ideas please consider opening a new issue or request.

Have a nice day!
