### ISSUE TITLE
Turn off pihole temporarily when new tab is opened

### ISSUE THREAD

**Issue by CBeast25** [badsgahhl/pihole-chrome-extension#18]
I use Tab for a Cause and whenever I want to open a new tab I have to remind myself to turn the pihole off manually.
Would it be possible to make this process automatic?

**Comment by badsgahhl** [comment]
I don't understand what you mean with "I use Tab"

**Comment by CBeast25** [comment]
This is [Tab for a Cause](https://chrome.google.com/webstore/detail/tab-for-a-cause/gibkoahgjfhphbmeiphbcnhehbfdlcgo?hl=en). Sorry I should have explained that.

But yea automatically disabling the pihole when a new tab is opened is what I was requesting.

**Comment by badsgahhl** [comment]
Implementation should be fine. I will try this out a little bit and how everything response then.
Will be an optional feature that can be activated in the settings i think.

**Comment by badsgahhl** [comment]
As it turns it this is something that won't work at all.

Chrome and Firefox understand only know "onTabCreated". So each tab created will turn off the pihole. Turning this option on would be the same as turning pihole generally off.
