### ISSUE TITLE
Switching server when multiple Pi-Hole have been set

### ISSUE THREAD

**Issue by puchijon** [badsgahhl/pihole-chrome-extension#19]
Hi,

I added a secondary Pi-Hole's server on the addon but I can't find the option to switch which Pi-Hole disable, or does it disable both ?

Using Chrome.

Regards

**Comment by badsgahhl** [comment]
Hey,

if you use multiple piholes all operations will be done simultaneously on all piholes at once.

**Comment by puchijon** [comment]
Oh, alright ! Thanks a lot
