### ISSUE TITLE
Request: Set previous disable time as next time

### ISSUE THREAD

**Issue by slvrscoobie** [badsgahhl/pihole-chrome-extension#2]
ok, so I like this but the 10s default is too short. 
If I set it to 30 or 60 or 300s is there a way for that to be "sticky" for the next time? Or an option to set a default? 
thanks!! :D Love it!

**Comment by badsgahhl** [comment]
Saw this already wanted in the previous project version. I will consider that for the next update.

What would you prefer more then? Setting a default value in the settings or keeping the last used value for the next time?
I think combining both is kind of impossible.

**Comment by slvrscoobie** [comment]
Agreed, i think they would be mutually exclusive. I agree with you, a customizable default would be perfect.

**Comment by badsgahhl** [comment]
Should go live with update 2.0.2. Currently 2.0.1 is under review at google. So i dont think the update will release before end of the next week.

**Comment by badsgahhl** [comment]
Wen't live.
