### ISSUE TITLE
Different colours for badge

### ISSUE THREAD

**Issue by piplongrun** [badsgahhl/pihole-chrome-extension#3]
Hi! Excellent addon! Would it be possible to change the colour of the badge on the icon to e.g. "On" = green, "Off" = grey, "Err" = red?

**Comment by badsgahhl** [comment]
Hey,
lovely idea! I checked the browser documentations and there's the possibility to include this feature to the extension.

Will be included into the next extension update ~2.0.6.

**Comment by badsgahhl** [comment]
Is now live with the update. Firefox is already released, chrome will take a week....

**Comment by piplongrun** [comment]
I just noticed it got updated because the "On" flag suddenly turned green :) Excellent and thank you very much for the update!
