### ISSUE TITLE
Stopped working after pi.hole updated to 5.0

### ISSUE THREAD

**Issue by spxak1** [badsgahhl/pihole-chrome-extension#4]
Worked nicely before the update.

Now I switch back and forth, no change, no "err" on icon. It seems pi.hole ignores it all together.

This is on Chrome.

Thanks!

**Comment by piplongrun** [comment]
I'm on 5.0 as well and it works great. Do you have the Pi-Hole address set to include `/admin`? That's what fixed it for me.

**Comment by spxak1** [comment]
Yes, I've had that from before the update. 
I will try again. 

Thanks for this. My wife will love it.

**Comment by badsgahhl** [comment]
@spxak1 Is it working now?

If the extension doesnt do anything and wont show errors it cannot resolve the ip. You can look at the erros on the background page if the problem still persists. This error handling will improve in further updates.

**Comment by spxak1** [comment]
Thanks for the help.  It still doesn't work. 
Completely ignored. Where is the "background page" to look for errors?

Thanks again.

**Comment by badsgahhl** [comment]
Just rightclick the icon and click "Manage Extensions". You should be on the page of the extension. In the middle of the screen should be a link "src/module/background/background.html".

**Comment by spxak1** [comment]
I think I got it. Sorry to have wasted your time. The first character of the API key was missing. Once this was corrected, I had set the time to 5 (which is seconds apparently and as such I was either missing it between on and off, or pi.hole was not responding at all). It seems to work now, but as a suggestion, make a not on the interface that the time is in seconds for dense people like me. 

Finally, before the update, when pi.hole was off, the stats showed 0 blocked sites (down from whatever 100.000 when on). Easy to see if working or not. 
After the update that number does not change, and the enabled/disabled with the timer on the side pane needs a refresh to appear.

So, resolved. Thanks again for your work and support.

**Comment by badsgahhl** [comment]
Nice that it workes now!

In the current version (Firefox released, Chrome in queue) the Popup gets a new UI showing the seconds better. But you are right in the options there is no unit, i will fix this.

**Comment by piplongrun** [comment]
Maybe, if possible, add a check for the length of the API key? It looks like it's always 64 characters long (SHA256?). Or even better check with a regex? `^[a-f0-9]{64}$`. That way if someone pastes in an incomplete or invalid key you know this is the issue.

**Comment by badsgahhl** [comment]
Had the same idea. At least there will be a warning if the key is not valid by this Regex Rule. Whitespaces are also a problem, they will be removed before. Should be possible to do this.
