### ISSUE TITLE
Support for multiple Pihole's

### ISSUE THREAD

**Issue by Kopernikus1979** [badsgahhl/pihole-chrome-extension#6]
Hi,

This extension is what I was looking for.
However I have to Pi-hole's running, and whith the plugin I can only disable 1.
So would it be possible to implement this?

Thx!

**Comment by badsgahhl** [comment]
Mhh, how do you imagine to control that?

Do you just mean to add one more server to the options and then the slider deactivates both at once?

Because i think otherwise this will be a mess in the UI.

**Comment by Kopernikus1979** [comment]
Hi, 

The simplest would be able to set two IP or hostnames so that the sliders deaactivates both Pi-holes.
Otherwise if I disable on 1 Pi-hole theirs a chanche the other Pi-hole resolves the querry.

Thx
