### ISSUE TITLE
Support to lists

### ISSUE THREAD

**Issue by dariusz-hub** [badsgahhl/pihole-chrome-extension#7]
If the API allows, there might be an option to add the site to the white / black list.

**Comment by badsgahhl** [comment]
Unfortunatly there is no PIHole Api point to do this.

The only way to do this would be writing a small php script and loading that on the server to execute the commands via the cli. 
I think blocklisting/whitelisting a website via the extension would be very cool. I will keep this in mind, but this won't be an upcoming feature the next time i think.

Maybe we can get some pihole devs to add these points to the api.

**Comment by dariusz-hub** [comment]
I looked a bit at the pihole code a bit and I see there is a method.

example request:

http://pi.hole:8085/admin/api.php?list=black&add=example.com&auth=here_api_key

list can be:

white
black
white_regex
white_wild
black_regex
black_wild
audit

**Comment by badsgahhl** [comment]
Insane! Is there any online documentation about this? The API documentation seems just old and not updated anymore. 

I will try this methods out. Hopefully that will work fluently in the extension!

**Comment by dariusz-hub** [comment]
I can see that there was also a sub method, but something probably went wrong.

example request:

http://pi.hole:8085/admin/api.php?list=black&sub=example.com&auth=here_api_key

https://github.com/pi-hole/AdminLTE/issues/1297

**Comment by PromoFaux** [comment]
>Maybe we can get some pihole devs to add these points to the api.

There is likely not going to be much more work done in terms of the PHP API, it was never really ideal to start with (hence not very well documented) Things will change on or around version 6.0 of Pi-hole with: https://github.com/pi-hole/FTL/pull/659

But, obviously no timelines. 

In the meantime I'll see what I can find out about the removal of the `sub` method

**Comment by badsgahhl** [comment]
I built now the first UI components and logic to solve this problem.
This is how it will probably look like:
![pihole2](https://user-images.githubusercontent.com/28596891/82608486-10b97280-9bbb-11ea-81ad-894d5ca8995f.JPG)

My plan was to show the Whitelist/Blacklist Button depending on the current state in the DB. But because of the missing API Points get.php this wont work.
Second problem was that having a domain directly on the blacklist, whitelisting it wont revert it. This can only be done by removing it via sub and then adding it to white. Or only removing it (Neither of this will work without the sub.php)

For testing and trying out please use the branch given and import the extension into your webbrowser via the dev-tools.
https://github.com/badsgahhl/pihole-chrome-extension/tree/v2.1-list-feature

**Comment by dariusz-hub** [comment]
Interesting idea. As if I had a moment of time, maybe I could add the missing methods, but I don't know what the development path is. I have no idea if the service in the new pihole will be through add / sub or by groups.

**Comment by badsgahhl** [comment]
Yea i saw this point in the groups, but i dont think authentification will work. As i have seen the code, you need a token which you get via the password authentification. 
But getting the password from the user in the extension wont work.

**Comment by dariusz-hub** [comment]
Dodałem kilka linijek kodu które powinny załatwić sprawę. Zobaczymy czy zostanie to zaakceptowane.

https://github.com/pi-hole/AdminLTE/compare/master...dariusz-hub:patch-1

**Comment by badsgahhl** [comment]
Very cool! Hope this will pass. The implementation you made suits the extension perfect.

**Comment by badsgahhl** [comment]
If you are interested in testing this feature, feel free to use this beta built here:
https://github.com/badsgahhl/pihole-chrome-extension/releases/tag/2.1.0-beta1

**Comment by PromoFaux** [comment]
@badsgahhl could you try your extension against the `new/api_add_sub_get_lists` branch, please? (`pihole checkout web new/api_add_sub_get_lists`) and let me know if it works for you?

**Comment by badsgahhl** [comment]
@PromoFaux Works like a charm! The only difference i noticed to the current api is the return message. At the moment if you add an already added domain via the api the return message is that it got skipped. With the branch i checked out, it always returns true, message null also while adding an already added domain. Maybe any kind of message like in the current api could be used at this message json attribute. But thats nothing that is needed that much, just a nice to have if possible.
